@startuml admin
skinparam actorStyle awesome
left to right direction
actor Admin
rectangle "System" as system #lightblue {
 (Login)
 (Open Database)
 (Add Product)
 (Remove Product)
 (Search Products)
 (Recent Orders)
 (Logout)
}
Admin --> (Login)
Admin --> (Open Database)
Admin --> (Add Product)
Admin --> (Remove Product)
Admin --> (Search Products)
Admin --> (Recent Orders)
Admin --> (Logout)
@enduml