@startuml admin
skinparam actorStyle awesome
left to right direction
actor Admin
rectangle "System" as system #lightblue {
 (Login)
 (Add Product)
 (Disable Product)
 (Enable Product)
 (Update Product)
 (View Products)
 (View Orders)
 (Logout)
}
Admin --> (Login)
Admin --> (Add Product)
Admin --> (Disable Product)
Admin --> (Enable Product)
Admin --> (Update Product)
Admin --> (View Products)
Admin --> (View Orders)
Admin --> (Logout)
@enduml