@startuml customer
skinparam actorStyle awesome
left to right direction
actor Customer
rectangle "System" as system {
  (Login)
  (Register)
  (View Cart)
  (Search Items)
  (View Orders)
  (Purchase Cart)
  (View Profile)
  (authentication.auth_tools)
  (View Wishlist)
  (Logout)
}
Customer --> (Login)
Customer --> (Register)
Customer --> (View Cart)
(View Cart) --> (Purchase Cart)
Customer --> (Search Items)
Customer --> (View Orders)
Customer --> (View Profile)
(View Profile) --> authentication.auth_tools
Customer --> (View Wishlist)
Customer --> (Logout)
@enduml